server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 20000
  servlet:
    context-path: /api/v1
spring:
  application:
    name: PizzaHut-be
  cache:
    type: redis
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  data:
    redis:
      host-port: ${REDIS_HOST_PORT:127.0.0.1:6379}
      password: ${REDIS_PASSWORD:30061999}
      db-default: ${REDIS_DB_DEFAULT:0}
      timeout: 60000
  jwt:
    secret: ${JWT-SECRET:XbHRcgAojNcOjzZkDZpZZp3o4oAr7rphVgF2J4r7XbnwvczlhWbRnN9gZ1RMkhObl9hXzwAW1qXMIqUXoUGyFH6JQkVvGgVka31gWJ8o9UCnqhKvRQIw3gOURsWwdGaGWM7rTM3TCEC7peVbPfnUCwSJ6GAbGVVA0QcUu5gDVe16eazgh44j8O9CDgpfNEb0SoCBUiUkAgiZaO9J1xwVQekdAQy3Sz2KRbg0nqI7rbP9Jz0iFygG4tvvvcV2U34eHxryGd4dXJerfpNZmJS4EOwWA4OS6zuYnFGBymwFT6CRVEE8qB}
    expire: ${JWT-EXPiRE:1209600000}
  messages:
    encoding: UTF-8

database:
  jdbcUrl : ${DB_URL:jdbc:mysql://localhost:3306/pizza-hut}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:30061999}

hikari:
  minimum-idle: 1500
  maximum-pool-size: 30000
  idle-timeout: 30000
  max-lifetime: 1800000
  connection-test-query: SELECT 1
  pool-name: ApiAppHikariPool
  driverClass: org.mariadb.jdbc.Driver
minio:
  url:
    public: ${ENDPOINT:http://localhost:9000}
  access:
    key: minio
  secret:
    key: miniostorage
  bucket: images
  region: us-east-1
  secure: false

